version: '3.8'

services:
  blog-articles:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://ibenmain:VY0yaivvyAC74D2L7pyECuEynRbvGPBoFmKHW4Kzw4W03EydUHwXa@localhost:5432/mydb
      NEXTAUTH_SECRET: "52e455dee7ec0e3e1cb8a4859cc474bf099bb15bcee407f1f2346359b9301500"
      NEXTAUTH_URL: http://localhost:3000
      NEXT_PUBLIC_API_URL: "http://localhost:3000"
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: ibenmain
      POSTGRES_PASSWORD: VY0yaivvyAC74D2L7pyECuEynRbvGPBoFmKHW4Kzw4W03EydUHwXa
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
