version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ibenmain
      POSTGRES_PASSWORD: VY0yaivvyAC74D2L7pyECuEynRbvGPBoFmKHW4Kzw4W03EydUHwXa
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - mynetwork

  nextjs:
    image: node:18
    container_name: Articles-blog
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://ibenmain:VY0yaivvyAC74D2L7pyECuEynRbvGPBoFmKHW4Kzw4W03EydUHwXa@postgres:5432/mydb
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
